name: my-work-flow
on:
  push:
    branches:
      - main

jobs:
  myjobe:
    runs-on: self-hosted

    steps:
      - name: mystep
        uses: actions/checkout@v4
      - name: print
        run: echo "hello "
